---
version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - errcheck
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - unused
  settings:
    staticcheck:
      checks:
        - all
        - '-ST1000'  # disable the rule SA1000 pkg comment
        - '-ST1020'  # Exported methods comment style
    revive:
      confidence: 0.8
      severity: warning
      enable-all-rules: true
      rules:
        - name: cyclomatic
          arguments:
            - 7
        - name: cognitive-complexity
          arguments:
            - 9
        - name: argument-limit
          arguments:
            - 5
        - name: line-length-limit
          arguments:
            - 120
        - name: function-length
          arguments:
            - 20
            - 0
        - name: function-result-limit
          arguments:
            - 3
        - name: var-naming
          arguments:
            - []
            - []
            - - upperCaseConst: true
          disabled: true
        - name: add-constant
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: banned-characters
          disabled: true
        - name: package-comments
          disabled: true
        - name: file-header
          disabled: true
        - name: exported
          disabled: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
